Add rolebinding controller
StatCan/aaw-profile-state-controller pull request #7
Opened 2022-04-25 19:38 UTC by saffaalvi

Resolves https://github.com/StatCan/daaas/issues/984

2022-04-25 20:59 UTC, Collinbrown95 requested changes
Good work! Just a few small fixes

2022-04-25 20:59 UTC, Collinbrown95 commented on pkg/controller/handler.go
> +	employeeDomains := [2]string{"cloud.statcan.ca", "statcan.gc.ca"} // Intialized with values
Consider making `employeeDomains` a global variable (because we might have a new domain in the future and want to update in only one place).

2022-04-25 20:59 UTC, Collinbrown95 commented on pkg/controller/handler.go
> +					break
Might be an opportunity to encapsulate the inner loop in a separate function.

Could write something similar to what you did here https://github.com/StatCan/aaw-profile-state-controller/pull/7/files#diff-54fe1371798f1e212124dbfe7803367d2bf18dc0738c8ed61719b024c6af2f15L15-R28 but to check if user is an employee or not.

2022-04-25 20:59 UTC, Collinbrown95 commented on pkg/controller/handler.go
> +	for _, roleBindings := range roleBindings {
The logic here could permit a non-employee to gain access to a SAS image. For example, suppose a non employee and an employee are in the same namespace. There would exist rolebindings associated with both the employee and non-employee, and the code below would set `nonEmployeeUser = false` if it detects the employee's rolebinding.

Instead this check should go in the opposite direction.

Assume `nonEmployeeUser := false` and if there exists a single counterexample, set `nonEmployeeUser := true` .


Example test case:

```yaml
kind: RoleBinding
# ...
subjects:
- name: alice@statcan.gc.ca
----
kind: RoleBinding
# ...
subjects:
- name: hacker@malicious.com
```

2022-05-03 14:33 UTC, blairdrummond approved these changes
LGTM!

2022-05-03 14:33 UTC, merged